name: Deploy React App to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
        - main

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
            node-version: 20
            cache: "npm"
        
      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build